# Generated by Django 5.0.6 on 2024-07-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_description_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('socio_type', models.CharField(choices=[('socio_activo', 'Socio Activo'), ('socio_cadete', 'Socio Cadete'), ('socio_menor', 'Socio Menor'), ('socio_interior_pais', 'Socio Interior País')], max_length=20)),
            ],
        ),
    ]
