# Generated by Django 5.0.6 on 2024-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_associate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('address_number', models.CharField(max_length=10)),
                ('tv_network', models.CharField(max_length=100)),
            ],
        ),
    ]
