# Generated by Django 5.0.6 on 2024-07-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_acreditation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acreditation',
            old_name='first_name',
            new_name='media_outlet',
        ),
        migrations.RenameField(
            model_name='acreditation',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='acreditation',
            old_name='tv_network',
            new_name='surname',
        ),
    ]
