# Generated by Django 5.0.6 on 2024-07-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acreditation',
            old_name='media_outlet',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='acreditation',
            old_name='address',
            new_name='direccion_domicilio',
        ),
        migrations.RenameField(
            model_name='acreditation',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='acreditation',
            old_name='address_number',
            new_name='numero_domicilio',
        ),
        migrations.RemoveField(
            model_name='acreditation',
            name='surname',
        ),
        migrations.AddField(
            model_name='acreditation',
            name='medio_televisivo',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
